### ISSUE TITLE
Use optimization flags and try many runs

### ISSUE THREAD

**Issue by Beliavsky** [alex-robinson/fortran-speed#2]
With gfortran on Windows, compiling on my PC with `gfortran looping_over_types.f90` as you did gave

```
Time using:   arrays:      1.30     s
Time using:  columns:      1.09     s
```
but compiling with `gfortran -O3 -flto -march=native looping_over_types.f90` usually gives a smaller difference, although the results differ from run to run. It may be a good idea to average the times of many runs or increase the problem size so that the random variation in timing is smaller than the variation due to code differences.

**Comment by alex-robinson** [comment]
Thanks for the hints. I had tried `-O3` without too much impact, but indeed your flags reduce the differences significantly. I have included this example in the latest README. I also increased the default number of iterations to make run times a bit higher.
